### ISSUE TITLE
Use list operations to simplify deck operations

### ISSUE THREAD

**Issue by barraponto** [MarcoWorms/Weed-card-game#5]
Issue #4 introduced list operations, allowing for `four_cards = 4 * ['MyCard']`.
That's cool, but we are still looping over `ndecks` to add the cards several times -- once per deck.
Instead, we could just have something like `deck = ndecks * deck`, don't you think?

**Comment by MarcoWorms** [comment]
Just commited the change, thanks for the tip. BTW I'm gonna work on shrinking that bunch of "if's" in the main game loop.
